theme: minima
title: HiramRV Site
description: Personal site for blog posts and project tracking.
lang: en
email: your.email@example.com
github_username: your-github-username
linkedin_username: your-linkedin-username
header_pages:
  - index.md
  - blog.md
  - programming-projects.md
  - other-projects.md
  - about.md
plugins:
  - jekyll-feed
