theme: minima
title: HiramRV Site
description: Personal site for blog posts and project tracking.
lang: en
email: stevenrv97@gmail.com
github_username: hiramRV
linkedin_username: stevenrv
header_pages:
  - index.md
  - blog.md
  - programming-projects.md
  - other-projects.md
  - about.md
plugins:
  - jekyll-feed
